Python Http Extension module
Azure-Samples/live-video-analytics-iot-edge-python pull request #26
Opened 2020-12-02 23:15 UTC by nicolasbotto

2020-12-02 23:23 UTC, naiteeks commented
@marc19997  - please review this PR

2020-12-09 00:09 UTC, ethanshea-ms requested changes
Many of the comments apply to both implementations

2020-12-09 00:09 UTC, ethanshea-ms commented on src/edge/modules/grpcExtension/app/inference_server.py
> +                    responseSeqNum += 1
This should always increment, otherwise multiple messages would be sent with the same sequence number

2020-12-09 00:09 UTC, ethanshea-ms commented on src/edge/modules/grpcExtension/app/main.py
> +            batchSize = _arguments.b[0]
Prefer argparse's default

https://stackoverflow.com/a/15301183/2496050

2020-12-09 00:09 UTC, ethanshea-ms commented on src/edge/modules/grpcExtension/docker/Dockerfile
> +COPY ./app/grpc-proto/*.py /app/
These should be after installing the dependencies. That way, code changes can be applied to the container quicker

2020-12-09 00:09 UTC, ethanshea-ms commented on src/edge/modules/grpcExtension/docker/Dockerfile
> +FROM base as final
Does this do anything?

2020-12-09 00:09 UTC, ethanshea-ms commented on src/edge/modules/grpcExtension/docker/Dockerfile
> +    apt-get install -y libgl1-mesa-dev
nit: combine with the install command above

2020-12-09 00:50 UTC, ethanshea-ms commented on src/edge/modules/grpcExtension/app/batchImageProcessor.py
> +class BatchImageProcessor():
This image processor does not process images in batch, it only processes them one at a time.

2020-12-09 01:41 UTC, ethanshea-ms commented on src/edge/modules/grpcExtension/app/inference_server.py
> +                if(messageCount < self.batchSize):
nit: Although it's not mentioned in PEP8, in python generally the parentheses are omitted in if statements

2020-12-09 19:13 UTC, nicolasbotto commented on src/edge/modules/grpcExtension/app/batchImageProcessor.py
> +    def ProcessImages(self, mediaStreamMessage, rawBytes, size):
I renamed all of them except the defined in the protobuf files

2020-12-10 18:16 UTC, naiteeks commented
@ethanshea-ms  - good to merge?

2020-12-11 21:05 UTC, naiteeks commented
@gadamilan  - for review

2020-12-11 23:24 UTC, merged